"project_id_env" : CROWDIN_PROJECT_ID
"api_token_env" : CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy" : true

"files": [
  {
    "source": "/user-guides/en-US/**/*.md",
    "translation": "/user-guides/%two_letters_code%-%locale%/**/%original_file_name%"
  }
]
